title: "Мой сайт"
description: "Добро пожаловать на мой сайт"
url: "https://kamaqiyasov.github.io"
baseurl: "/-github-pages-task3"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
